global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-ai'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']

    grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - '3000:3000'
      volumes:
        - grafana-storage:/var/lib/grafana
      networks:
        - spring-ai
networks:
  spring-ai:
    driver: bridge

  volume:
    grafana-storage:

#      jaeger:
#        image: jaegertracing/all-in-one:latest
#        ports:
#          - "16686:16686"
#          - "4317:4317"
#          - "4318:4318"
#        environment:
#          - COLLECTOR_OTLP_ENABLED=true
#        networks:
#          - spring-ai
#
#    networks:
#      spring-ai:
#        driver: bridge
#
#    volumes:
#      grafana-storage: